// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfeqwekzwtjvzkqcphdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZXF3ZWt6d3RqdnprcWNwaGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTg3MTgsImV4cCI6MjA2NDg3NDcxOH0.6U7ByO3TzDu8msOlNLu25ACuzZ935wi8Z7o6cYedwhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);